spring:
  application:
    name: crm-dexter-backend
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/crm_dexter}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:Kevin20##}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
server:
  port: ${SERVER_PORT:8080}
  error:
    include-message: always

app:
  frontend-url: ${FRONTEND_URL:http://localhost:5173}
  jwt:
    secret: hWECRrGIJQckGPfyEqGxesnfYlEz71nw5Ci14VEqLGt
    expiration-ms: 86400000
  otp:
    expiration-seconds: ${OTP_EXPIRATION_SECONDS:300}
  emailjs:
    service-id: ${EMAILJS_SERVICE_ID:service_8uxwfjw}
    template-id: ${EMAILJS_TEMPLATE_ID:template_tvavw6v}
    public-key: ${EMAILJS_PUBLIC_KEY:3C-4-tQn2-lJzNuyt}
    private-key: ${EMAILJS_PRIVATE_KEY:DxHc9ijMxtRjfABi93QBR}
